### ISSUE TITLE
emscripten-module-wrapper dependency issue

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/emscripten-module-wrapper#22]
Following along with the tutorial using coindrop repo. Got to this step and failed:

```
node ~/emscripten-module-wrapper/prepare.js simple.js --file input.data --file output.data
```

The error:
```
module.js:557
    throw err;
    ^

Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/hswick/emscripten-module-wrapper/prepare.js:3:12)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

It seems that this dependency is not found. I noticed that there was no package.json in this repo. Adding a package.json with needed dependencies would make it easier. Then users can clone this repo, run npm install, and continue.

**Comment by hswick** [comment]
ipfs-api needed to be installed as well

**Comment by hswick** [comment]
Hard coded path causing IO error

```
Error: ENOENT: no such file or directory, open '/home/sami/emscripten-module-wrapper/pre-run.js'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at Object.<anonymous> (/home/hswick/emscripten-module-wrapper/prepare.js:22:17)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
```
